### ISSUE TITLE
```calc section headers are not recognized in files with CRLF line endings

### ISSUE THREAD

**Issue by tdietel** [mofosyne/QuickMathJS#16]
I noticed the bug when I used the VS Code QuickCalc extension on Windows: the extension did not recognize ```calc section headers in the files. Instead, the entire file would be processed, inserting invalid text where it was not intended.
I have als tested it on a Mac, where the problem did not occur. 

I suspected an issue with CRLF line endings on Windows vs LF on Mac and changed the encoding of the file from CRLF to LF in VS Code. After the modification, the file is processed as expected.

**Comment by tdietel** [comment]
I also investigated a possible cause of the problem, and it appears to be due to quickmath.js lines 91 and 115, where the regular expressions only look for '\n' (LF) but not for '\r\n' (CRLF).
I think a change from `\n` to '\r?\n' in these lines should do the trick. I did not check any other files if they need similar treatment. 
I have no way to test the changes myself (I'm not familiar with javascript and VS code extensions) and therefore cannot easily test the changes, otherwise I would submit a PR.

**Comment by mofosyne** [comment]
* https://open-vsx.org/extension/mofosyne/quickcalc
* https://marketplace.visualstudio.com/items?itemName=mofosyne.quickcalc

Just updated to v1.2.1 with https://github.com/mofosyne/QuickMathJS/commit/5d33a257894d09fcb278635720a2b83fd3279b5d 

Can you check if this is working for you? Basically added the regex changes you suggested and then also added eol handling then added test cases for it...

**Comment by tdietel** [comment]
Thanks. I checked and the extension now behaves as expected on Windows as well.

**Comment by mofosyne** [comment]
@tdietel glad it's working for you. Any thoughts about it so far? This compared to other in the VSCode marketplace is certainly quite minimalistic, but I'm hoping it will still prove to be useful in it's own way!
